Description: >
    This template deploys two different Amazon Kinesis Streams we need for the architecture.
Parameters:
    # Como me van a llegar los parametros
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String
    KinesisShardsNumber: 
        Description: "Select the number of shards"
        Type: Number
Resources:
  KinesisRT:
    Type: 'AWS::Kinesis::Stream'
    Properties:
      Name: !Sub ${EnvironmentName}-KinesisRT # Toma el nombre del environment y le agrega KinesisRT que le pasamos desde la plantilla Master
      RetentionPeriodHours: 24
      ShardCount: 
        !Ref KinesisShardsNumber # Toma el numero de shards que le pasamos desde la plantilla Master
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-RealTime # Le agrega el nombre del environment y RealTime al Kinesis Stream


Outputs: # Despues de creado el recurso, va a coger los valores y lo va a exportar a cloudformation
  # esto nos sirve para conectar otros cloud formatios que se puedan conectar plantillas

  KinesisRT:
    Description: A reference to the Kinesis Stream containing all events from reactive application.
    Value: !Ref KinesisRT

